Setting and purging global variables via admin api #1354
mockoon/mockoon pull request #1363
Opened 2024-04-19 20:57 UTC by sakshi4321

**Technical implementation details**

I have implemented the `setGlobalVars` and `purgeGlobalVars` endpoints for the admin API and introduced two public methods that modify the global variables. Additionally, I updated the ordering of the middleware to accommodate the `parseBody` middleware, which is used to populate ` request.body.`

I have updated the documentation. 

**Checklist**

- [x] data migration added (@mockoon/commons)
- [x] commons lib tests added (@mockoon/commons)
- [x] commons-server lib tests added (@mockoon/commons-server)
- [x] CLI tests added (@mockoon/cli)
- [x] desktop UI automated tests added (@mockoon/desktop)

<[https://github.com/mockoon/mockoon/issues/1354](https://github.com/mockoon/mockoon/issues/1354)>

Closes #{1354}

2024-04-19 22:57 UTC, sakshi4321 commented
@255kb please review this PR. it addresses: #1354

2024-04-20 07:13 UTC, 255kb commented
Thanks for opening the PR. 

I think I prefered the endpoints paths as you propose in the issue: `/admin-api/global-vars`, so we stick with dash case and have a more RESTy approach. The `/admin-api/state` should stay a route to purge the whole state, not a parent of other resources I think.

I suggest the following paths instead: 

- PURGE /mockoon-admin/state
- POST /mockoon-admin/state/purge
- `POST|PUT|PATCH /mockoon-admin/global-vars`: add/update a variable
- `PURGE /mockoon-admin/global-vars`: remove all the global vars
- `POST/mockoon-admin/global-vars/purge`: remove all the global vars --> the reason for this second endpoint is that PURGE method is often filtered by web application firewalls. 

Could you also add the purging of the global variables to the main `PURGE /admin-api/state` route? 
I will add more remarks on the code itself. 

Thank you!

2024-04-20 07:20 UTC, 255kb requested changes

2024-04-20 07:20 UTC, 255kb commented on packages/commons-server/src/libs/server/admin-endpoint.ts
> +      console.error('Error handling request:', err);
the console.error will be lost, you should use the logger instead. But I think the call response is enough and we could remove this.

2024-04-20 07:20 UTC, 255kb commented on packages/commons-server/src/libs/server/admin-endpoint.ts
> +      res.status(500).send({ message: 'Failed to retrieve global variable' });
```suggestion
      res.status(500).send({ message: 'Failed to purge global variables' });
```

2024-04-20 07:20 UTC, 255kb commented on packages/commons-server/src/libs/server/server.ts
> +    );
This could be simplified to:
```suggestion
    this.globalVariables= {};
```

2024-04-20 07:20 UTC, 255kb commented on packages/commons-server/src/libs/server/server.ts
> +        }
Could you add a call to `this.purgeGlobalVariables` here, so the full state is purged?

2024-04-20 07:20 UTC, 255kb commented on packages/commons-server/src/libs/server/admin-endpoint.ts
> +      console.log(err);
the console.error will be lost, you should use the logger instead. But I think the call response is enough and we could remove this.

2024-04-22 06:25 UTC, 255kb commented
Just saw you updated the PR, thanks. But why remove the PUT and PATCH routes? They were good I think! Even if they are technically doing the same thing as the POST route, it's better to follow REST semantics.

2024-04-25 07:55 UTC, 255kb commented
Don't bother about macos tests not passing, they are flaky since the latest Electron/webdriverio update. The two other (win/linux) are passing so it's good.

2024-04-27 17:47 UTC, sakshi4321 commented
@255kb I have updated the docs and the API endpoints

2024-04-27 23:46 UTC, sakshi4321 reviewed
Added admin api endpoints , tests

2024-04-28 08:37 UTC, 255kb commented
Perfect, thanks for the changes. This will be in next week release.

2024-04-28 08:37 UTC, merged