#611 Issue: secure flag not removing from set cookie fix
mockoon/mockoon pull request #1564
Opened 2024-10-23 14:54 UTC by Sanidhyafeaturist

## Fix: Remove `Secure` Flag from `Set-Cookie` Headers When Proxying over HTTP

### Issue Overview
When Mockoon proxies requests to an HTTPS service that sets cookies with the `Secure` flag, the `Secure` flag was not removed when the response was proxied over HTTP. This behavior could lead to insecure environments being unable to store or manage cookies correctly.

### Changes Made

1. **Modified `setHeaders` Function:**
   - The `setHeaders` function now checks for `Set-Cookie` headers. If a `Set-Cookie` header is found and contains the `Secure` flag, it is stripped out when the request is proxied over HTTP.
   - Added logic to safely remove the `Secure` flag using:
     ```ts
     if (isSetCookie) {
       parsedHeaderValue = parsedHeaderValue.replace(/;\s*Secure/i, '');
     }
     ```

2. **Updated Proxy Middleware (`createProxyMiddleware`):**
   - Integrated an `onProxyRes` handler to intercept the response from the proxied HTTPS service. The handler inspects the `Set-Cookie` headers and removes the `Secure` flag if present.
   - Added the following to the proxy configuration:
     ```ts
     onProxyRes: (proxyRes, req, res) => {
       const setCookieHeaders = proxyRes.headers['set-cookie'];
       if (setCookieHeaders) {
         proxyRes.headers['set-cookie'] = setCookieHeaders.map((cookie) =>
           cookie.replace(/;\s*Secure/i, '')
         );
       }
     }
     ```

### Impact
With these changes, Mockoon will now properly handle secure cookies when proxying requests over HTTP by removing the `Secure` flag from the `Set-Cookie` headers. This ensures that cookies are stored and managed correctly in environments where HTTPS is not used on the client-side.

2024-10-24 15:55 UTC, Saucistophe commented
If you edit your title and mention #611, the issue and PR will be linked automagically.

2024-10-25 10:01 UTC, Sanidhyafeaturist commented
> If you edit your title and mention #611, the issue and PR will be linked automagically.

I think you linked it so I don't need to mention the issue

2024-10-25 13:37 UTC, Saucistophe reviewed
I haven't tested yet.
You have useless files commited, I'm pretty sure it's an error...?

2024-10-25 13:41 UTC, 255kb commented on package.json
> +    "typescript": "5.6.3"
Yes, no need to add TS at the monorepo root level

2024-10-25 13:48 UTC, 255kb requested changes
@Sanidhyafeaturist  As pointed by @Saucistophe there are some issues with your PR. 

At the beginning your work looked on the right track. I don't want to be blunt, but the more you commit the less it seems to make sense:

- You added TS at the monorepo root level, which is not needed. 
- You added a Grunt workflow in the CI which is not required and adds nothing to the existing CI. It's also not necessary for the scope of this change. 
- you forgot to remove git conflicts symbols `======`
- you completely broke the proxy config:

![image](https://github.com/user-attachments/assets/c4e2a932-dd75-4817-a010-a7486ee3ab57)

I must admit that I am a bit confused. 
You will also have to test thoroughly and add automated tests. Considering the code you wrote, I don't think you tested it yet.

2024-10-25 14:36 UTC, Sanidhyafeaturist commented
actuall the files I added here are like just for test purposes and once all the changes are final I will remove them

2024-10-26 18:37 UTC, Saucistophe commented
Now you've deleted essential project files. Please consult your git history, and ensure you commit only what's necessary for the bug!

2024-10-27 03:59 UTC, Sanidhyafeaturist commented
> Now you've deleted essential project files. Please consult your git history, and ensure you commit only what's necessary for the bug!

Wdym I deleted essential project files?

2024-10-27 04:00 UTC, Sanidhyafeaturist commented
But are my changes ready to merge or not?

2024-10-27 11:15 UTC, Sanidhyafeaturist commented
> Now you've deleted essential project files. Please consult your git history, and ensure you commit only what's necessary for the bug!

I added them back

2024-10-27 13:18 UTC, 255kb requested changes

2024-10-27 13:18 UTC, 255kb commented on .npmrc
Please add back this file

2024-10-27 13:18 UTC, 255kb commented on packages/commons-server/src/libs/server/server.ts
You merged main into your branch, but you likely made a mistake during the merge, as http-proxy-middleware was updated to the latest version. Now, the events listeners are not name `onProxyReq` or `onProxyRes` anymore, but they are part of a parent object `on`:

```js
on: {
  proxyRes: ...
  proxyReq: ...
}
```

I suggest that you restart your changes from the latest main, just to add the required changes. Also, your code needs to be formatted with Prettier (VSCode extension) and respect indentation to avoid showing all the code as a change.

2024-10-27 14:15 UTC, Sanidhyafeaturist commented
ok then I will restart

2024-10-27 14:15 UTC, closed without merging

2024-10-27 14:16 UTC, 255kb commented
You can keep the PR opened, and "redo" your code locally and push.

2024-10-27 14:27 UTC, Sanidhyafeaturist commented
nah, I ma create a new pr

2024-10-27 14:44 UTC, Sanidhyafeaturist commented
you should check pr #3395