Add option to export selected environment to JSON
mockoon/mockoon pull request #346
Opened 2020-10-10 16:15 UTC by gVirtu

**Description**

Adds the **Export current environment to a file (JSON)** option to the Import/export menu in Mockoon's format.
The implementation in Import/Export Service is based off `exportAllEnvironments`, except the active environment is retrieved instead of the whole environments list.
To reduce code duplication a little, the `exportDataToFilePath` function was extracted from `exportAllEnvironments` and reused in `exportActiveEnvironment`.

**Related Issue**

Import/export selected environment only https://github.com/mockoon/mockoon/issues/251

**Motivation and Context**

Implementing the feature mentioned in the related issue (#251).

**How Has This Been Tested?**

A second environment fixture was added to `test/data/export/environments.json`.
The test for exporting all environments was adapted to verify that the data for both environments is present in the file.
The test for exporting the active environment is very similar to it, except it selects the first environment with a context menu click and makes sure it was exported. 

**Screenshots (if appropriate):**

![image](https://user-images.githubusercontent.com/15658199/95658616-27bd1a80-0af2-11eb-8ae1-2bfd3f5b3f21.png)

**Closing issues**

closes #251

2020-10-10 19:04 UTC, 255kb requested changes
Thank you for your contribution, it's very clean! 😃 
Only one small change you will see in the comments, and also could you please add the following code to the [`electron-main.js` after line 419](https://github.com/mockoon/mockoon/blob/90798f5e775d8ee79413224cb88736a43de4d7fb/src/electron-main.js#L419):
`menu.items[2].submenu.items[0].submenu.items[3].enabled = state;`
This is to disable the export menu when no environments are present.

Then we are ready to merge! 
Thank you again.

2020-10-11 15:22 UTC, gVirtu commented
Sure thing! Changes are up. :)

2020-10-12 19:24 UTC, 255kb approved these changes

2020-10-12 19:27 UTC, 255kb commented
Perfect, thank you :) 
It will be in the next release

2020-10-12 20:26 UTC, merged