feat: enhancement the app can enable random status code
mockoon/mockoon pull request #356
Opened 2020-10-29 09:49 UTC by Thanakorn-ki

Relate issue: #269 

# Feature
Enhance the random status code feature. When checked enable random status code the app will random status from the create response.

![image](https://user-images.githubusercontent.com/17230930/97551868-18046800-1a06-11eb-852b-49da61ac5686.png)

# Screenshot

![Guideline enable status](https://user-images.githubusercontent.com/17230930/97551494-a1676a80-1a05-11eb-9c00-f938de09c205.jpg)

2020-10-29 12:27 UTC, 255kb requested changes
Hi @Thanakorn-ki Thank you for contributing. 
Could you please comment on the #269 issue so I can assign it to you? 

Also, I would like to discuss the placement of the checkbox. I think this should not be at the top with the route options but next to the responses list. Maybe we could remove the text from the "Add response" button and put it in a tooltip, and add another button with an icon, which could be toggled on/off. 
But I need to find an icon as the shuffle icon (the two crossed arrows) from the material design icons pack has already been used for the CORS options. 
![image](https://user-images.githubusercontent.com/7489814/97573286-cbab2f00-19e9-11eb-84bc-1a72757d09ec.png)

I also have several remarks concerning the implementation:
- I would rename `enableRandomStatusCode` to `randomResponse` as we are not really randomizing a "status code" inside a response but rather a response inside a route. I hope it makes sense. 
- Also we will need a new migration no. 13 in the migration lib + a migration test in `test/data/migrations/13`
- I saw you update all the environment test files, and I thank you for this, I know it's a pain and not really straightforward. I would like at one point to create a small script to take care of this, but I didn't have time yet :) However, after you create the migration no. 13 you will also have to update the `lastMigration` property in all these files. And last thing, you shouldn't add the new property `enableRandomStatusCode` (or `randomReponse`) to the test files that are in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`. These test environments files are here to test migrations/imports from old versions so they shouldn't be modified at all. 

Thank you for your time and help :)

2020-10-29 13:05 UTC, Thanakorn-ki commented
> Hi @Thanakorn-ki Thank you for contributing.
> Could you please comment on the #269 issue so I can assign it to you?
> 
> Also, I would like to discuss the placement of the checkbox. I think this should not be at the top with the route options but next to the responses list. Maybe we could remove the text from the "Add response" button and put it in a tooltip, and add another button with an icon, which could be toggled on/off.
> But I need to find an icon as the shuffle icon (the two crossed arrows) from the material design icons pack has already been used for the CORS options.
> ![image](https://user-images.githubusercontent.com/7489814/97573286-cbab2f00-19e9-11eb-84bc-1a72757d09ec.png)
> 
> I also have several remarks concerning the implementation:
> 
> * I would rename `enableRandomStatusCode` to `randomResponse` as we are not really randomizing a "status code" inside a response but rather a response inside a route. I hope it makes sense.
> * Also we will need a new migration no. 13 in the migration lib + a migration test in `test/data/migrations/13`
> * I saw you update all the environment test files, and I thank you for this, I know it's a pain and not really straightforward. I would like at one point to create a small script to take care of this, but I didn't have time yet :) However, after you create the migration no. 13 you will also have to update the `lastMigration` property in all these files. And last thing, you shouldn't add the new property `enableRandomStatusCode` (or `randomReponse`) to the test files that are in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`. These test environments files are here to test migrations/imports from old versions so they shouldn't be modified at all.
> 
> Thank you for your time and help :)

Thank you for your suggestion and I will fix it.

2020-10-29 13:24 UTC, Thanakorn-ki commented
@255kb 
Are you ok this?
When we want to shuffle response this icon adds the color green and then we don't shuffle the default color of the app.

![image](https://user-images.githubusercontent.com/17230930/97579352-8b1cd700-1a24-11eb-87b7-aa686df1fa3a.png)

2020-10-29 13:25 UTC, Thanakorn-ki commented
> @255kb
> Are you ok this?
> When we want to shuffle response this icon adds the color green and then we don't shuffle the default color of the app.
> 
> ![image](https://user-images.githubusercontent.com/17230930/97579352-8b1cd700-1a24-11eb-87b7-aa686df1fa3a.png)

Or check icon ?

![image](https://user-images.githubusercontent.com/17230930/97579591-d1723600-1a24-11eb-9a53-5ba1ccb0ec55.png)

2020-10-29 14:00 UTC, 255kb commented
@Thanakorn-ki I like the green/not green icon, but I wonder would prefer to use the blue color when activated, so it's consistent with the rest of the app. Also, could you please keep the two buttons and the dropdown part of the `btn-group` so there is no gap between them?
Concerning this icon, it's the perfect one for symbolizing randomness, but it is used for the CORS option right now. Maybe we should find something else for the CORS from the icons set https://material.io/resources/icons/?style=baseline
But I wonder what?

2020-10-29 14:14 UTC, 255kb commented
I also think we should say more in the tooltip, maybe "Random response (will disable the rules)", and add an orange message inside the rules saying "Activating random responses disable the rules"
The message could be similar to the one above the body when a file is selected:
![image](https://user-images.githubusercontent.com/7489814/97585387-62331c80-19f9-11eb-99f5-2375c4de1c56.png)

2020-10-29 14:16 UTC, Thanakorn-ki commented
> I also think we should say more in the tooltip, maybe "Random response (will disable the rules)", and add an orange message inside the rules saying "Activating random responses disable the rules"
> The message could be similar to the one above the body when a file is selected:
> ![image](https://user-images.githubusercontent.com/7489814/97585387-62331c80-19f9-11eb-99f5-2375c4de1c56.png)

OK, it makes sense

2020-10-29 14:22 UTC, 255kb commented
Don't bother changing the CORS icon for now, use the "shuffle" icon for your feature and I will do the changes to the CORS option after.

2020-10-29 16:03 UTC, Thanakorn-ki commented
@255kb 
Last implement.

![image](https://user-images.githubusercontent.com/17230930/97599622-c924f580-1a3a-11eb-8649-dc4132f670a9.png)

2020-10-29 19:52 UTC, 255kb requested changes
Thank you for the changes, I made some comments. 
I'm sorry for the confusion on the yellow warning message, and for all the requested changes on the tests. I know it's a pain 😆 
If you want I can take it from here for the last details, let me know 👍

2020-10-29 19:52 UTC, 255kb commented on src/app/app.component.html
> +                                [ngClass]="{'text-primary': getRandomResponse()}"
you should directly use `activeRoute.randomResponse` which is available there through an `async` pipe line 238:

```suggestion
                                [ngClass]="{'text-primary': activeRoute.randomResponse}"
```

2020-10-29 19:52 UTC, 255kb commented on src/app/app.component.html
> +
I'm sorry, maybe what I suggested wasn't clear at all, but this message shouldn't be here which is reserved for body related messages. Instead, put it inside the "Rules" tab content at the top. I only suggested that you use the same design  than the body message. 
Something like 
```
<div class="text-warning text-center">Activating random responses disable the rules</div>
```

2020-10-29 19:52 UTC, 255kb commented on src/app/app.component.ts
> +  }
Remove as you will directly use `activeRoute` in the template.

(As a general rule, method calls should be avoided inside templates as they can have bad performances. This is mainly due to the change detection which will call the method each time something change even if the data returned by the method didn't change)

2020-10-29 19:52 UTC, 255kb commented on src/app/stores/actions.ts
> +}
You don't need to create a new action as you can use `updateRouteAction()`

2020-10-29 19:52 UTC, 255kb commented on src/app/stores/actions.ts
> +  TOGGLE_RANDOM_RESPONSE
You don't need to create a new action as you can use updateRouteAction()

2020-10-29 19:52 UTC, 255kb commented on src/app/app.component.ts
> +      toggleRandomResponse(uuid)
please use `updateRouteAction()`
```suggestion
  public toggleRandomResponse(randomResponse: boolean) {
    this.store.update(
      updateRouteAction({ randomResponse: !randomResponse })
```

2020-10-29 19:52 UTC, 255kb commented on src/app/stores/reducer.ts
> +    }
Not needed if you use `updateRouteAction`

2020-10-29 19:52 UTC, 255kb commented on test/data/import/new/full-export.json
> +                        "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/import/new/route-export.json
> +              "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/import/old/1.5.1.json
> +                    "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/import/old/1.6.0-single-env.json
> +              "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/import/old/1.6.0-single-route.json
> +      "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/import/old/1.6.0.json
> +                    "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/migrations/10/environments.json
> +        "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/migrations/11/environments.json
> +        "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/migrations/12/environments.json
> +        "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/migrations/13/environments.json
> +    "lastMigration": 13,
This migration test should start from 12

2020-10-29 19:52 UTC, 255kb commented on test/data/migrations/13/environments.json
> +        "randomResponse": false,
Do not add `randomResponse` property as we actually need to test the migration

2020-10-29 19:52 UTC, 255kb commented on test/data/migrations/9/environments.json
> +        "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/migrations/incompatible/environments.json
> +        "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-29 19:52 UTC, 255kb commented on test/data/migrations/pre-1.7.0/environments.json
> +        "randomResponse": false,
Please do not modify files in `test/data/migrations`, `test/data/import/new` and `test/data/import/old`

2020-10-30 07:11 UTC, 255kb approved these changes
Thank you for the modification.
I will take it from here and change the CORS icon. 

Thank you again for your contribution 🥳

2020-10-30 07:11 UTC, merged