Add response.statusMessage data information in environment logs
mockoon/mockoon pull request #853
Opened 2022-11-02 18:31 UTC by AndreiOrmanji

This may solve #852

**Technical implementation details**
I've been added a new property  `statusMessage` in `Transaction.response` located in `packages\commons\src\models\server.model.ts` for getting the statusMessage in "Logs" tab and some other places:
 - `function CreateTransaction` in packages\commons-server\src\libs\utils.ts that converts a pair of `Request` and `Response` objects in a `Transaction` object
 - `EnvironmentLogResponse` in packages\desktop\src\renderer\app\models\environment-logs.model.ts for showing the information from modified `Transaction` in "Logs" tab
 - `function formatLog` in packages\desktop\src\renderer\app\services\data.service.ts for converting the `Transaction` object in 
`EnvironmentLogResponse` object.
- added a new item in "General" section of "Response" tab in packages\desktop\src\renderer\app\components\environment-logs\environment-logs.component.html
- updated existing tests for covering my changes.

**Disclaimer:**
I'm not an experienced open software contributor or at least a JS developer, but I want to help you, Mockoon supporters, to make your 

**Checklist**

- [ ] data migration added (@mockoon/commons)
- [ ] data migration automated tests added (@mockoon/commons)
- [ ] CLI automated tests added (@mockoon/cli)
- [ ] desktop automated tests added (@mockoon/desktop)

2022-11-02 18:35 UTC, AndreiOrmanji commented
I don't know if I'm allowed to mark any item in checklist as "solved", so I've left it all "as is".

2022-11-05 08:34 UTC, 255kb commented on packages/desktop/src/renderer/app/components/environment-logs/environment-logs.component.html
> +                    <strong>StatusMessage:</strong> {{ selectedLog.response?.statusMessage }}
Maybe title could be more human readable:
```suggestion
                    <strong>Status message:</strong> {{ selectedLog.response?.statusMessage }}
```

2022-11-05 08:35 UTC, 255kb requested changes
Thanks for the contribution. 
I run the CI and there are some Prettier formatting issue. Please run Prettier before pushing again. I also add a comment concerning the log label.

2022-11-07 14:15 UTC, 255kb commented
Now that I am thinking about it, I think it would be better to display the Status message next to the status code, so it's more in line with what other tools like Curl are displaying. What do you think?

2022-11-07 15:28 UTC, AndreiOrmanji commented
> Now that I am thinking about it, I think it would be better to display the Status message next to the status code, so it's more in line with what other tools like Curl are displaying. What do you think?

In my optinion,it will "break existing UI consistency" where you have already 'General', 'Headers', 'Body' sections.
If you are ok with adding more details, I can add HTTP version, send in response by server (probably can be useful for other users).

2022-11-08 19:04 UTC, 255kb commented
> > Now that I am thinking about it, I think it would be better to display the Status message next to the status code, so it's more in line with what other tools like Curl are displaying. What do you think?
> 
> In my optinion,it will "break existing UI consistency" where you have already 'General', 'Headers', 'Body' sections. If you are ok with adding more details, I can add HTTP version, sent in response by server (probably can be useful for other users).

What I meant was to add the message next to the status code to avoid adding a new line, like this:
```
Status: 404 - Not Found
```

Instead of:
```
Status: 404
Status message: Not Found
```
I'm not sure if adding the HTTP version is really useful. Wouldn't it be always something like 1.1 as we are using Node.js' http?

2022-11-09 07:47 UTC, AndreiOrmanji commented
> > > Now that I am thinking about it, I think it would be better to display the Status message next to the status code, so it's more in line with what other tools like Curl are displaying. What do you think?
> > 
> > 
> > In my optinion, it will "break existing UI consistency" where you have already 'General', 'Headers', 'Body' sections. If you are ok with adding more details, I can add HTTP version, sent in response by server (probably can be useful for other users).
> 
> What I meant was to add the message next to the status code to avoid adding a new line, like this:
> 
> ```
> Status: 404 - Not Found
> ```
> 
> Instead of:
> 
> ```
> Status: 404
> Status message: Not Found
> ```

Your varians looks good too :)


> I'm not sure if adding the HTTP version is really useful. Wouldn't it be always something like 1.1 as we are using Node.js' http?

It depends on server the requests are sent to. For example, persistent connection (read more at https://developer.mozilla.org/en-US/docs/Web/HTTP/Connection_management_in_HTTP_1.x) is available from 1.1 and higher, so it can be useful to know what version is supported by server.

2022-11-09 16:34 UTC, AndreiOrmanji commented
> If you don't mind, maybe display status code and message on one line, I think I prefer 🙂 Also, if you want to display the HTTP version go for it!

I want to add HTTP version. Can you add an example how it would look like?

2022-11-09 16:42 UTC, 255kb commented
Maybe something like:

```
Protocol: HTTP1.1
Status: 404 - Not found
```

So it's ready for other protocols like web socket **when** we will implement web sockets 😄.

2022-11-12 10:29 UTC, AndreiOrmanji commented
> Maybe something like:
> 
> ```
> Protocol: HTTP1.1
> Status: 404 - Not found
> ```
> 
> So it's ready for other protocols like web socket **when** we will implement web sockets smile.

I've implemented like so:
![image](https://user-images.githubusercontent.com/48985454/201470013-cb80b9c4-d88c-480e-9dad-e4257f5fcb5a.png).

2022-11-14 15:51 UTC, AndreiOrmanji commented
Sorry for pipeline fails, but I could not set up project on my machine to execute tests from pipeline...
Fixed problem caused pipeline fail.

2022-11-15 07:23 UTC, 255kb commented
No worries, I used the CI all the time to run the tests 😅
There are still many test that fail, apparently for an extra ":". 
You can run the test locally by running first `npm run build:desktop:ci` then `npm run test:desktop -- --spec "environment-logs.spec.ts"`.
Let me know if you need help with anything.

2022-11-28 18:19 UTC, AndreiOrmanji commented
It seems that node js and express did not provide access to protocol and version to send in response, so I've set values from request, where it was possible.
I would remove `Protocol` section because i'm not sure it was implemented in a "correct" way and to be implemented by someone  who has more experience with JS and node.

I've refused to use docker. With windows I've the following error on test running:
```bash
$ npm -v
8.19.2

$ node -v
v19.0.0

$ nvm -v
Running version 1.1.9.
```
Screenshot:
![image](https://user-images.githubusercontent.com/48985454/204351100-efbb247e-c20a-479f-b7ef-428ece0a4a33.png)

2022-11-30 09:55 UTC, 255kb commented
> I would remove `Protocol` section because i'm not sure it was implemented in a "correct" way and to be implemented by someone who has more experience with JS and node.

I would say the same. Maybe remove it and stick to the status message only? It's probably too much hassle for the benefits right now.

2022-11-30 17:17 UTC, AndreiOrmanji commented
> Maybe remove it and stick to the status message only? It's probably too much hassle for the benefits right now.

Removed changes, related to `Protocol`, so the current version looks like:
![image](https://user-images.githubusercontent.com/48985454/204864472-9998b9a8-f412-408b-9d70-499f3bb8dcca.png)

2022-12-01 08:46 UTC, 255kb approved these changes

2022-12-01 08:47 UTC, 255kb commented
Thank you for the changes. Everything looks ok, I will merge and add it to the next release (probably later this month).

2022-12-01 08:58 UTC, AndreiOrmanji commented
Thank you very much

2022-12-01 09:42 UTC, merged